### ISSUE TITLE
Iframe scrolling with IOS

### ISSUE THREAD

**Issue by erming** [erming/resume-editor#10]
While this editor isn't fit for mobile devices, it looks pretty good on tablets.

However, IOS has a native "bug". You can't scroll iframes by default. I've not found a good way to solve this without introducing some other weird behaviour in other browsers.

If anyone know a simple solution to fix this, it would be great.

**Comment by JaredCubilla** [comment]
If you add `-webkit-overflow-scrolling:touch` to the parent div it should work.

Source: http://davidwalsh.name/scroll-iframes-ios

**Comment by erming** [comment]
I did try adding scrolling to the parent. I used `overflow-y: scroll;` on the parent, but that didn't
work very well.

Here's a screenshot from the link you provided:
![iframe_problem](https://cloud.githubusercontent.com/assets/2502500/4079301/cd4f637e-2ed3-11e4-8ccb-0221059ef14e.png)

_As you can see, there's two different scrollbars visible._ 

But `-webkit-overflow-scrolling` is iOS only. I'll give it a shot!

Thanks for taking the time, @JaredCubilla!

**Comment by erming** [comment]
There. I've fixed it.

As you can see in the commit (referenced above this answer), I had to add a wrapper and add `-webkit-overflow-scrolling` and `overflow: auto`.

However, this fix does not work flawlessly for every browser (it adds an extra scrollbar on desktop web browsers). But I found a workaround: using a media query targeting only smaller devices.

Closing this issue now.
