### ISSUE TITLE
Clear editor/start from scratch

### ISSUE THREAD

**Issue by PragTob** [erming/resume-editor#14]
Thanks for doing this at first :)

I just wanted to use the editor, but it really bothers me that every field is already filled - I want to start from scratch and not have to delete everything by hand.

Therefore a `clear` button would be nice - I thought reset might do that but it resets to the initial input :)

Maybe the feature is there and I'm just blind.

**Comment by erming** [comment]
Your commit has made its way to http://registry.jsonresume.org/. 

I removed the "Reset" button completely. Resetting can be done by refreshing the page anyway. And having two buttons ("Reset" and "Clear") was just confusing.

The cache on http://registry.jsonresume.org/ is currently serving an old version of the javascript, so the button does not currently work, but should be resolved very soon (probably before you even see this post).

I'll close this issue. Thanks!
