### ISSUE TITLE
Link broken?

### ISSUE THREAD

**Issue by flyfy1** [erming/resume-editor#26]
Heroku says no such app when visit page: http://registry.jsonresume.org/

**Comment by decentral1se** [comment]
It's back up, looks like you can close this one off @flyfy1

**Comment by erming** [comment]
Oh, sorry, I didn't see this issue until now.

http://registry.jsonresume.org/ is being hosted together with the other apps run by [jsonresume](github.com/jsonresume) who just had some problems with Heroku. But now it's up and running again.

Thanks for reporting in!
