### ISSUE TITLE
http://registry.jsonresume.org/ is not working

### ISSUE THREAD

**Issue by rfabro** [erming/resume-editor#33]
![image](https://user-images.githubusercontent.com/11796900/38594784-a062a646-3d7a-11e8-8885-962293d55b74.png)

**Comment by rfabro** [comment]
Closing as the registry.jsonresume.org site is now functioning.

**Comment by nikking** [comment]
@rfabro the website is down again.

**Comment by rfabro** [comment]
> @rfabro the website is down again.

@thomasdavis has been working on [this ](https://github.com/jsonresume/resume-website/issues/50)
