### ISSUE TITLE
registry.jsonresume.org is down

### ISSUE THREAD

**Issue by devoredevelops** [erming/resume-editor#35]
I thought it was just for me at first, but it appears that registry.jsonresume.org is down: https://www.isitdownrightnow.com/registry.jsonresume.org.html

It was up and worked when trying to reach my personal resume as soon as two months ago. I'm curious if others have seen similar behavior and what can be done to ameliorate the issue. Thanks.

**Comment by thomasdavis** [comment]
So sorry, bringing it back up now.

**Comment by devoredevelops** [comment]
Works now, thanks!
