### ISSUE TITLE
Questionable permission-level

### ISSUE THREAD

**Issue by shaedrich** [erming/resume-editor#36]
What do you need that excessive permissions for? I thought, you just need to read from a simple gist?

![grafik](https://github.com/user-attachments/assets/79143cf1-63cc-4e56-9043-45be85fc9814)

**Comment by thomasdavis** [comment]
@shaedrich do you mean this to be on the new repo https://github.com/jsonresume/jsonresume.org/ ? 

If so, can you recreate the issue as it is valid

**Comment by shaedrich** [comment]
Oh, okay. Thanks for the hint :+1:

(see jsonresume/jsonresume.org#138)
