### ISSUE TITLE
Exported JSON does not conform to resume schema

### ISSUE THREAD

**Issue by thomastoye** [erming/resume-editor#7]
When exporting (clicking `#export`), the exported JSON does not conform to the schema.

Returned (invalid) JSON:

```
{
    "resume": {
        "basics": {
            ...
        },
        ...
    }
}
```

Expected JSON:

```
{
    "basics": {
        ...
    },
    ...
}
```

**Comment by erming** [comment]
Discussion here: https://github.com/erming/resume-editor/pull/8
Fixed here: https://github.com/erming/resume-editor/commit/447932e0ccbfab3ff8686d0e5c549ed453e782e1
