### ISSUE TITLE
JSON Highlighting and Readability

### ISSUE THREAD

**Issue by JaredCubilla** [erming/resume-editor#9]
Could we make the JSON textarea font, something other than the default monospace font? Monaco looks good.

Also, I was thinking, is it possible that we can add syntax highlighting to the JSON?

**Comment by erming** [comment]
Hey!
Good ideas.

The font is just some CSS that needs to change. I'm not really sure what fonts looks good for different operating systems. But here's what GitHub uses:

```
textarea {
    font-family: Consolas, "Liberation Mono", Menlo, Courier, monospace;
}
```

..

And yeah, highlighting should be possible. This is what GitHub uses:
http://ace.c9.io/

However, that's an extra 200-300kb (I think).

**Comment by JaredCubilla** [comment]
Oh I see. I think we should go with the font changing, but I guess we should decide whether those extra 200-300 kb is worth it.

**Comment by erming** [comment]
I've implemented the font rules.

I'll think about adding the editor, but will close this issue for now.
